### ISSUE TITLE
Contribute LR finder to Ignite contrib

### ISSUE THREAD

**Issue by vfdev-5** [ItamarWilf/super-convergence#1]
Hi @ItamarWilf 
It would great if you could send a PR with `LRFinder` to Ignite contrib. What do you think ?

PS. Created an issue for that in Ignite: https://github.com/pytorch/ignite/issues/590

**Comment by itamarwilf** [comment]
No problem, I can work on a separate ignite Engine version of the finder. The code here is more of a decoration for single supervised model, using lr_finder and one cycle policy as implemented in fast.ai.
